### ISSUE TITLE
how to use window.open(url) on php-webkit

### ISSUE THREAD

**Issue by ghost** [baconface/php-webkit#23]
Hi All,

i can't use  height and width not same what i want on window.open(url, "_blank", "toolbar=no, scrollbars=yes, resizable=yes, top=50, left=500, width=400, height=400")

also i have try win.open(url, "_blank", "toolbar=no, scrollbars=yes, resizable=yes, top=50, left=500, width=400, height=400") 

i see on folder "php-webkit" already use 
var gui     = require('nw.gui');
var win     = gui.Window.get();

but why can't use win.open() ?
i thing need use 
var gui     = require('nw.gui');
var win     = gui.Window.get();
on .php where on it.

but still can't open window.

any body please help.
Thank You

**Comment by baconbrad** [comment]
win.open is not working for you for 2 reasons.
1. Your app doesn't have access to our instance of win. When the PHP program is loaded we redirect to your program. Thus destroying the win object.
2. win is the window object for NW.js. You are acting as if it is the standard window global object. NW.js's win.open usage is different.

You have two options:
1. Use the [window.open()](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) object that works the way you intend it to.
2. Use the [win.open()](https://github.com/nwjs/nw.js/wiki/window#openurl-options) object using the way NW.js requires it to be.

Unless you want to use NW.js's window policy settings it makes more sense to use option 1.
