### ISSUE TITLE
Blank Page After Starting Application Screen

### ISSUE THREAD

**Issue by 2braincells2go** [baconface/php-webkit#24]
I have been trying to get this working for few days. Everything seems to go fine, get past the starting application page and then a blank page is shown.

Can't seem to get past this point and cannot find any logs for troubleshooting. I have a the phpinfo script in the application folder.

Is there something you can think of to help me solve this issue?

Many thanks for your input and sharing this with us.

**Comment by baconbrad** [comment]
I am no longer supporting this project but I will see if I can help.

Can you verify your PHP install works outside of php-webkit?
Does your php.ini restrict phpinfo()?
What version of NW.js are you using?
What platform are you running on?

**Comment by mosiyash** [comment]
I just try the library ...

2016-02-08 8:33 GMT+06:00 Brad Metcalf notifications@github.com:

> I am no longer supporting this project but I will see if I can help.
> 
> Can you verify your PHP install works outside of php-webkit?
> Does your php.ini restrict phpinfo()?
> What version of NW.js are you using?
> What platform are you running on?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/baconface/php-webkit/issues/24#issuecomment-181167712
> .

## 

C уважением, Никита Мосияш
nikita.mosiyash@gmail.com

**Comment by 2braincells2go** [comment]
Thank you Brad. Pretty sure you hit right on issue of php.ini restricting phpinfo. Never thought of that and should have tried simple php file.

Got issues displaying files, but it all boils down to me getting under the hood:)

Appreciate you taking time to input.
