### ISSUE TITLE
How can I pass something from php-webkit/main.js to application/index.php

### ISSUE THREAD

**Issue by visualbadger** [baconface/php-webkit#28]
Is any possibility to pass data from main.js to application/index.php ? I have a little project that requires arduino and I use serialport in main.js to take data from arduino and with socket.io I want to emit that data to application/index.php .

This is my socket.io test function in main.js

```
var io = require('socket.io').listen(server);
function sendTime() {
    io.emit('time', { time: new Date().toJSON() });
}
setInterval(sendTime, 100);
```

This is my function from index.php:

```
socket.on('time', function(data) {
console.log(data.time);
});
```

**Comment by baconbrad** [comment]
You are going to have to look into a standard AJAX solution more than likely. Your NW.js app is the client running a server. So you basically need to have that client pass data to the server.
