### ISSUE TITLE
Travis tests for pull requests

### ISSUE THREAD

**Issue by wookiecooking** [baconface/php-webkit#3]

**Comment by baconbrad** [comment]
I am inexperienced with Travis CI. But I am welcoming to the idea.

**Comment by wookiecooking** [comment]
Setting up travis-CI isn't too trivial, [check out this guide](http://shapeshed.com/continuously-deploy-node-apps-with-github-travis-and-heroku/) we would be using it a bit different (mainly for tests and linting) since nw.js would need to be on travis. 

I'll take a look tomorrow to see how nw.js handles this.
